# Run continuous integration

on:
  push:
    branches:
      - 'main'  # Only run on push to main branch
  pull_request:
    branches:
      - 'main'  # Only run on PRs targeting main branch
    types: [opened, synchronize, reopened]  # Specify PR events to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: false
          cache: 'maven'
      - name: Build with Maven
        run: 'mvn package'
        shell: bash
